version: "3.1"

services:
    prestashop:
        image: prestashop/prestashop
        ports:
            - 7777:80
        volumes:
            - ./prestashop:/var/www/html
#        environment:
#            DB_SERVER: db
#            DB_PASSWD: password
#            PS_INSTALL_AUTO: 1
#            PS_ENABLE_SSL: 0
#            PS_LANGUAGE: fr
#            PS_COUNTRY: FR
#            PS_ALL_LANGUAGES: 1
#            ADMIN_MAIL: 'jf.dirienzo@gmail.com'
#            ADMIN_PASSWD: 'password'
        networks:
            - prestashop-network
        depends_on:
            -   db

    db:
        image: 'mariadb:10.6.4'
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: prestashop
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            - prestashop-network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
        networks:
            - prestashop-network

networks:
    prestashop-network:
        driver: bridge